### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by emptymalei** [NeuPhysics/neutrino#1]
First of first
- [x] Review Haxton's review

---
- [ ] MAA
- [x] Master equation
- [ ] MSW Triangle !  Similar to  http://tberg.dk/post/neutrino-oscillations-the-msw-triangle/
    ![image](https://cloud.githubusercontent.com/assets/663798/11644552/41ce8662-9d0a-11e5-8503-44d6e69f87fb.png)
    What I need is:
  - [ ] Adiabatic conversion: Survival probability at each distance. An gif or something with a slider.
  - [ ] Non-adiabtic
- [ ] [FAQ](https://github.com/NeuPhysics/neutrino/issues/10)
